Add lyric-panel.
emacs-eaf/eaf-music-player pull request #23
Opened 2023-05-20 05:48 UTC by ShaoChenHeng

2023-05-20 06:31 UTC, ShaoChenHeng commented
发现两个问题：
1.今天调试的时候发现albumArt不生效了，不知道是不是我的网络问题。
2.暂停一会儿音乐，再继续播放，音乐的速度会发生变化，一下快一下慢。这个问题在我调试歌词功能的时候一直有，不知道是不是之前的代码导致了这个问题，以前都不会的。

2023-05-20 06:42 UTC, manateelazycat commented
感谢大佬，我下周看一下哈

2023-05-20 06:57 UTC, manateelazycat commented
感谢大佬，我下周来看补丁

2023-05-21 02:45 UTC, manateelazycat commented
Can you upload a screenshot to here? Thanks.

2023-05-21 06:16 UTC, manateelazycat requested changes

2023-05-21 06:16 UTC, manateelazycat commented on buffer.py
> +        print(self.port);
这个调试代码去掉吧。

2023-05-21 06:49 UTC, ShaoChenHeng commented on buffer.py
> +        print(self.port);
ok

2023-05-21 06:57 UTC, ShaoChenHeng commented
[![lyric.png](https://i.postimg.cc/9MJpq4yW/lyric.png)](https://postimg.cc/tZnPK4rf)

2023-05-21 07:22 UTC, manateelazycat commented
歌词是什么方式触发的呀？

2023-05-21 07:49 UTC, ShaoChenHeng commented
发生切歌，获取这首歌的歌词;
每过去一秒，筛选出歌词里时间小于等于当前时间的所有歌词，拿到这些筛选歌词中的最后一个，如果当前歌词和最后一个歌词一样，那就不滚动;否则更新当前歌词，然后并对当前行的歌词上下几行进行更新，滚动歌词。

2023-05-21 08:13 UTC, manateelazycat commented
> 发生切歌，获取这首歌的歌词; 每过去一秒，筛选出歌词里时间小于等于当前时间的所有歌词，拿到这些筛选歌词中的最后一个，如果当前歌词和最后一个歌词一样，那就不滚动;否则更新当前歌词，然后并对当前行的歌词上下几行进行更新，滚动歌词。

我的意思是歌词这个界面和列表这个界面的位置重合， 他们俩是怎么切换的呀？

2023-05-21 08:28 UTC, ShaoChenHeng commented
新添加了一个Main组件，打开播放器Main里面默认是显示PlayList + Panel，然后通过快捷键C-l，就可以切换成LyricPanel + Panel

2023-05-21 11:29 UTC, manateelazycat commented
> 新添加了一个Main组件，打开播放器Main里面默认是显示PlayList + Panel，然后通过快捷键C-l，就可以切换成LyricPanel + Panel

PlayList 和 LyricsPanel 是可以一起来回切换的吗？

2023-05-21 13:52 UTC, merged

2023-05-21 14:02 UTC, manateelazycat commented
我本地测试， 每次 Ctrl + l 的时候， 都会得到错误

```
vue.runtime.esm.js:3047 TypeError: this.currentLyric.filter is not a function
    at a.currentTime (LyricPanel.vue:67:1)
    at Un (vue.runtime.esm.js:3015:30)
    at t.run (vue.runtime.esm.js:3532:21)
    at Yr (vue.runtime.esm.js:4119:17)
    at Array.<anonymous> (vue.runtime.esm.js:3141:20)
    at Jn (vue.runtime.esm.js:3063:16)
```