Waiting for server.js connected, use thread.
emacs-eaf/eaf-music-player pull request #29
Opened 2023-06-10 14:23 UTC by ShaoChenHeng

2023-06-10 14:26 UTC, manateelazycat requested changes

2023-06-10 14:26 UTC, manateelazycat commented on buffer.py
> +        server_thread = threading.Thread(target=self.init_server)
这里要添加一个 self.thread_queue.append(server_thread), 要不 Python 有个问题是， 一旦作用域消失以后， 它会主动清理函数临时变量， 包括 server_thread, 就会导致报错。

2023-06-10 14:47 UTC, ShaoChenHeng commented on buffer.py
> +        server_thread = threading.Thread(target=self.init_server)
ok

2023-06-10 22:38 UTC, manateelazycat requested changes

2023-06-10 22:38 UTC, manateelazycat commented on buffer.py
> +        self.thread_queue = []
上面有 thread_quite 的定义

2023-06-11 04:01 UTC, ShaoChenHeng commented on buffer.py
> +        self.thread_queue = []
ok

2023-06-11 05:06 UTC, merged